import { InputForm } from '@/components/InputForm'

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center px-4">
      <div className="absolute left-6 top-6">
        <div className="flex items-center gap-2">
          <span className="text-2xl" aria-hidden="true">
            🚀
          </span>
          <span className="font-semibold text-gray-900">AI PM Copilot</span>
        </div>
      </div>

      <div className="w-full max-w-2xl text-center">
        <h1 className="text-5xl font-semibold tracking-tight text-gray-900">
          From Challenge to
          <br />
          <span className="text-indigo-600">Complete PM Artifacts</span>
        </h1>
        <p className="mx-auto mt-4 max-w-md text-lg text-gray-500">
          Describe your product challenge and get a PRD, competitive analysis,
          roadmap, and executive summary — all generated by AI.
        </p>

        <div className="mt-10">
          <InputForm />
        </div>
      </div>
    </main>
  )
}
